apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2048
  labels:
    app: 2048
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 2048
  template:
    metadata:
      labels:
        app: 2048
    spec:
      containers:
        - name: devopshint
          image: 058264111032.dkr.ecr.ap-south-1.amazonaws.com/devopshint:1.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080